# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheGrintTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheGrintTestApp
    pod 'Alamofire'
    pod 'SDWebImage'

  target 'TheGrintTestAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheGrintTestAppUITests' do
    # Pods for testing
  end

end
